apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
    spec:
      containers:
      - name: spring-backend
        image: 211125419724.dkr.ecr.eu-west-3.amazonaws.com/ecr-backend:latest  
        ports:
        - containerPort: 8080  
---
apiVersion: v1
kind: Service
metadata:
  name: spring-backend-service
spec:
  type: NodePort
  selector:
    app: spring-backend
  ports:
    - protocol: TCP
      port: 8080  
      targetPort: 8080  
      nodePort: 30000  
